/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.grupo10.supermarket.views;

import com.grupo10.mvc.DataTableModel;
import com.grupo10.mvc.IRenderData;
import com.grupo10.supermarket.models.Customer;
import com.grupo10.supermarket.models.SuperMarket;
import java.util.ArrayList;
import java.util.Collection;

/**
 *
 * @author jeiss
 */
public class Customers extends javax.swing.JPanel implements IRenderData<Collection<Customer>> {

    /**
     * Creates new form Customers
     */
    public Customers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        superMarketFilterComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        postitionFilterTextField = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        setupTableModel();
        customersTable = new javax.swing.JTable();
        customerEditor = new com.grupo10.supermarket.views.CustomerEditor();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Super Market:");

        jLabel2.setText("Postition");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(superMarketFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postitionFilterTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(superMarketFilterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(postitionFilterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        customersTable.setModel(customersTableModel);
        jScrollPane1.setViewportView(customersTable);

        jSplitPane1.setRightComponent(jScrollPane1);
        jSplitPane1.setLeftComponent(customerEditor);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.grupo10.supermarket.views.CustomerEditor customerEditor;
    private javax.swing.JTable customersTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    public javax.swing.JTextField postitionFilterTextField;
    public javax.swing.JComboBox<SuperMarket> superMarketFilterComboBox;
    // End of variables declaration//GEN-END:variables

    private final DataTableModel<Customer> customersTableModel = new DataTableModel<>();
    
    private void setupTableModel() {
        customersTableModel.addColumn("First Name", (customer, index, name) -> customer.getName());
        customersTableModel.addColumn("Last Name", (customer, index, name) -> customer.getLastname());
        customersTableModel.addColumn("Identification", (customer, index, name) -> customer.getIdentification());
        customersTableModel.addColumn("Telephone", (customer, index, name) -> customer.getTelephone());
        customersTableModel.addColumn("Position", (customer, index, name) -> customer.getPosition());
    }
    
    @Override
    public void renderData(Collection<Customer> data) {
        customersTableModel.setData(new ArrayList<>(data));
    }
}
