/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.grupo10.supermarket.views;

/**
 *
 * @author jeiss
 */
public class SuperMarkets extends javax.swing.JPanel {

    /**
     * Creates new form SuperMarkets
     */
    public SuperMarkets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        superMarketsTable = new javax.swing.JTable();
        superMarketEditor1 = new com.grupo10.supermarket.views.SuperMarketEditor();

        setLayout(new java.awt.BorderLayout());

        superMarketsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "City", "Actions"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(superMarketsTable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
        add(superMarketEditor1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.grupo10.supermarket.views.SuperMarketEditor superMarketEditor1;
    private javax.swing.JTable superMarketsTable;
    // End of variables declaration//GEN-END:variables
}
